const DefaultTheme = {
    dark: false,
    colors: {
        background: 'white',
        primaryBtnColor: '#0C7BDC',
        primaryBtnShadow: '#005AB5',
        btnText: 'white',
        text: '#1E1E1E',
        fadedText: '#696969',
        dialogueBG: '#F9F9F9',
        dialogueBorder: '#C8C8C8',
        optionBtn: {
            blue: '#0C7BDC',
            blueShadow: '#005AB5',
            red: '#E84A34',
            redShadow: '#C33C2A',
            green: '#10CA23',
            greenShadow: '#079515',
            yellow: '#EFB00C',
            yellowShadow: '#CD9300'
        },
        navBG: '#005AB5',
        navText: 'white',
        inputBG: '#E9E9E9',
        inputBorder: '#A4A4A4',
        progBarFill: '#0C7BDC',
        progBarBG: '#CDDDEC',
        diaProgFill: '#0C7BDC',
        diaProgBG: '#CDDDEC',
        cardBGOne: '#5d9cd4',
        cardBGTwo: 'white',
        cardBorder: '#005AB5',
        switchBG: '#CDDDEC',
        switchThumb: '#3366FF',
        headerColour: '#393939',
        chartBarLabel: '#0C7BDC',
        chartBarColor: '12, 123, 220',
        textColour: '#1E1E1E',
        toggleBoxColor: '#CDDDEC'
    },
    colorBlindColors: {
        primaryColor: '#584B9D',
        primaryColorShadow: '#262262',
        primaryColorFade: '#9893b8',
        switchThumb: '#584B9D',
        progBarFill: '#262262',
        progBarBG: '#9893b8',
        cardBGOne: '#584B9D',
        cardBGTwo: 'white',
        cardBorder: '#262262',
        navBG: '#584B9D',
    }
}

export default DefaultTheme;